create table if not exists public.radical (
    id bigint generated by default as identity primary key,
    char text not null,
    radicalnumber integer not null,
    stroke_count integer not null
);

-- 設置 RLS 策略
alter table public.radical enable row level security;

do $$ 
begin
    if not exists (select 1 from pg_policies where tablename = 'radical' and policyname = 'Enable read access for all users') then
        create policy "Enable read access for all users" on public.radical
            for select
            to authenticated, anon
            using (true);
    end if;

    if not exists (select 1 from pg_policies where tablename = 'radical' and policyname = 'Enable insert for authenticated users only') then
        create policy "Enable insert for authenticated users only" on public.radical
            for insert
            to authenticated
            with check (true);
    end if;

    if not exists (select 1 from pg_policies where tablename = 'radical' and policyname = 'Enable update for authenticated users only') then
        create policy "Enable update for authenticated users only" on public.radical
            for update
            to authenticated
            using (true)
            with check (true);
    end if;

    if not exists (select 1 from pg_policies where tablename = 'radical' and policyname = 'Enable delete for authenticated users only') then
        create policy "Enable delete for authenticated users only" on public.radical
            for delete
            to authenticated
            using (true);
    end if;
end $$;
